import type { TranslationSchema } from './en';

export const ar: TranslationSchema = {
  common: {
    appName: 'بروبرتي بالس',
    cancel: 'إلغاء',
    save: 'حفظ',
    retry: 'إعادة المحاولة',
    seeAll: 'عرض الكل',
    loading: 'جارٍ التحميل…',
    error: 'حدث خطأ ما',
    search: 'ابحث عن منطقة أو عقار…',
    currency: 'ج.م',
    verified: 'موثّق',
    readyToMove: 'جاهز للسكن',
    offPlan: 'تحت الإنشاء',
    startingFrom: 'يبدأ من',
    viewMap: 'عرض الخريطة',
    demoMode: 'الوضع التجريبي — اربط Supabase للتشغيل الفعلي',
  },
  tabs: {
    home: 'الرئيسية',
    search: 'بحث',
    ai: 'الذكاء',
    portfolio: 'المحفظة',
    profile: 'حسابي',
  },
  auth: {
    welcome: 'مرحبًا بعودتك',
    welcomeSub: 'سجّل الدخول إلى لوحة استثماراتك',
    createAccount: 'أنشئ حسابك',
    createSub: 'ابدأ رحلتك في الاستثمار العقاري الفاخر اليوم.',
    createAccountCta: 'إنشاء الحساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'أدخل اسمك الكامل',
    investorType: 'نوع المستثمر',
    investorIndividual: 'فردي',
    investorInstitutional: 'مؤسسي',
    investorFamilyOffice: 'مكتب عائلي',
    termsPrefix: 'بإنشائك حسابًا، فإنك توافق على',
    terms: 'شروط الخدمة',
    privacy: 'سياسة الخصوصية',
    and: 'و',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    login: 'تسجيل الدخول',
    continueWithGoogle: 'المتابعة عبر جوجل',
    or: 'أو',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    forgotPassword: 'نسيت كلمة المرور؟',
    confirmEmail: 'تحقق من بريدك لتأكيد الحساب ثم سجّل الدخول.',
    signOut: 'تسجيل الخروج',
    emailRequired: 'يرجى إدخال بريد إلكتروني صحيح',
    passwordRequired: 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    nameRequired: 'يرجى إدخال اسمك',
  },
  home: {
    greetingMorning: 'صباح الخير',
    greetingAfternoon: 'مساء الخير',
    greetingEvening: 'مساء الخير',
    welcomeBack: 'مرحبًا بعودتك',
    portfolioValue: 'قيمة المحفظة',
    netYield: 'صافي العائد',
    properties: 'العقارات',
    aiInsight: 'رؤية الذكاء الاصطناعي',
    aiInsightBody:
      'من المتوقع ارتفاع عوائد العقارات التجارية في القاهرة الجديدة بنسبة 15% الربع القادم. فكّر في إعادة توزيع رأس المال السكني.',
    viewStrategy: 'عرض الاستراتيجية',
    topOpportunities: 'أفضل الفرص',
    marketActivity: 'نشاط السوق',
    rentalIncome: 'دخل الإيجار',
    mortgagePayment: 'قسط الرهن',
  },
  search: {
    title: 'فرص استثمارية',
    subtitle: '{{count}} عقار يطابق استراتيجية محفظتك',
    filters: {
      price: 'السعر',
      type: 'النوع',
      bedrooms: 'الغرف',
    },
    noResults: 'لا توجد عقارات. جرّب تعديل عوامل التصفية.',
    dealScore: 'تقييم الصفقة',
  },
  detail: {
    pulseScore: 'مؤشر بالس',
    projectedRoi: 'العائد المتوقع',
    grossYield: 'العائد الإجمالي',
    ltvRatio: 'نسبة التمويل',
    riskLevel: 'مستوى المخاطر',
    aiThesis: 'أطروحة الاستثمار بالذكاء الاصطناعي',
    highlights: 'مميزات العقار',
    location: 'الموقع',
    beds: 'غرف',
    baths: 'حمامات',
    area: 'المساحة',
    addToPortfolio: 'أضف إلى المحفظة',
    inPortfolio: 'في المحفظة',
    generateReport: 'إنشاء تقرير',
    riskLow: 'منخفض',
    riskModerate: 'متوسط',
    riskHigh: 'مرتفع',
  },
  chat: {
    title: 'المستشار الذكي',
    online: 'متصل',
    today: 'اليوم',
    greeting:
      'مرحبًا! لقد حللت محفظتك الحالية. ارتفع عائد أصولك العقارية بنسبة 6.2% هذا الربع. هل تريد تفصيلًا لأفضل العقارات أداءً؟',
    placeholder: 'اسأل عن عقاراتك…',
    suggestions: {
      risks: 'مخاطر السوق؟',
      diversify: 'تنويع المحفظة',
      tax: 'الأثر الضريبي',
    },
  },
  portfolio: {
    title: 'محفظتك',
    updated: 'تحديث الأداء لشهر {{month}}',
    totalValue: 'إجمالي قيمة الأصول',
    avgYield: 'متوسط العائد',
    cashFlow: 'التدفق النقدي',
    equityGrowth: 'نمو حقوق الملكية',
    last6: 'آخر 6 أشهر',
    holdings: 'الممتلكات',
    manage: 'إدارة المحفظة',
    transactions: 'سجل المعاملات',
    empty: 'لا توجد ممتلكات بعد. استكشف الفرص للبدء.',
  },
  profile: {
    title: 'حسابي',
    account: 'الحساب',
    preferences: 'التفضيلات',
    theme: 'المظهر',
    themeLight: 'فاتح',
    themeDark: 'داكن',
    themeSystem: 'النظام',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    adminDashboard: 'لوحة الإدارة',
    notifications: 'الإشعارات',
    about: 'حول التطبيق',
    member: 'عضو منذ {{date}}',
  },
  admin: {
    title: 'لوحة الإدارة',
    label: 'لوحة الإدارة',
    welcomeBack: 'مرحبًا بعودتك، {{name}}',
    director: 'المدير',
    overview: 'نظرة عامة',
    totalUsers: 'إجمالي المستخدمين',
    users: 'المستخدمون',
    listings: 'العقارات',
    reports: 'التقارير',
    revenue: 'الإيرادات',
    totalProperties: 'العقارات',
    activeToday: 'النشطون اليوم',
    recentActivity: 'النشاط الأخير',
    viewAll: 'عرض الكل',
    recentUsers: 'أحدث المستخدمين',
    manageProperties: 'إدارة العقارات',
    manageUsers: 'إدارة المستخدمين',
    searchUsers: 'ابحث عن مستخدم…',
    changeRole: 'تغيير الصلاحية',
    roleUpdated: 'أصبحت صلاحية {{name}} الآن {{role}}',
    roleError: 'تعذّر تحديث الصلاحية',
    cannotSelf: 'لا يمكنك تغيير صلاحيتك بنفسك.',
    role: 'الصلاحية',
    joined: 'تاريخ الانضمام',
    noAccess: 'ليس لديك صلاحية الإدارة.',
    roles: {
      investor: 'مستثمر',
      consultant: 'مستشار',
      admin: 'مدير',
    },
    activity: {
      report: 'أنشأ تقرير عائد الربع الثالث',
      listing: 'أضاف عقارًا جديدًا',
      profile: 'حدّث الملف الاستثماري',
      discrepancy: 'أبلغ عن تعارض في عقار',
    },
  },
  payment: {
    title: 'الدفع',
    selectedPlan: 'الباقة المختارة',
    perMonth: '/شهريًا',
    method: 'طريقة الدفع',
    card: 'بطاقة',
    vodafone: 'فودافون كاش',
    fawry: 'فوري',
    cardHolder: 'اسم حامل البطاقة',
    cardHolderPlaceholder: 'الاسم الكامل على البطاقة',
    cardNumber: 'رقم البطاقة',
    expiry: 'تاريخ الانتهاء',
    cvv: 'CVV',
    saveCard: 'احفظ بيانات البطاقة لدفع أسرع',
    subscriptionFee: 'رسوم الاشتراك',
    serviceTax: 'ضريبة الخدمة (14%)',
    orderTotal: 'الإجمالي',
    payNow: 'ادفع {{amount}} الآن',
    secure: 'دفع آمن مشفّر بـ SSL 256-bit',
    vodafoneHint: 'سيتم تحويلك للتأكيد عبر محفظة فودافون كاش.',
    fawryHint: 'سيتم إنشاء كود فوري للدفع من أي منفذ.',
    success: 'تم الدفع بنجاح',
    successBody: 'اشتراك {{plan}} مُفعّل الآن.',
    failed: 'فشل الدفع. حاول مرة أخرى.',
    pending: 'الدفع قيد التأكيد.',
    phone: 'رقم محفظة الموبايل',
    upgrade: 'ترقية الباقة',
    planName: 'الذكاء المؤسسي',
    feature1: 'تحليل تقلبات السوق بالذكاء الاصطناعي لحظيًا',
    feature2: 'محاكاة غير محدودة لعوائد العقارات',
    feature3: 'وصول مباشر لمستشار بشري مختص',
  },
  report: {
    title: 'تقرير الاستثمار',
    generating: 'جارٍ إنشاء التقرير…',
    recommendation: 'التوصية',
    confidence: 'ثقة {{value}}%',
    summary: 'الملخص',
    keyMetrics: 'المؤشرات الرئيسية',
    grossYield: 'العائد الإجمالي',
    netYield: 'صافي العائد',
    capRate: 'معدل الرسملة',
    cashOnCash: 'العائد النقدي',
    monthlyCashFlow: 'التدفق النقدي الشهري',
    fiveYearRoi: 'عائد 5 سنوات',
    riskLevel: 'مستوى المخاطر',
    buy: 'شراء',
    hold: 'احتفاظ',
    avoid: 'تجنّب',
    generatedAt: 'أُنشئ في {{date}}',
  },
  transactions: {
    title: 'سجل المعاملات',
    empty: 'لا توجد معاملات بعد.',
    rental: 'دخل الإيجار',
    mortgage: 'قسط الرهن',
    purchase: 'شراء عقار',
    subscription: 'اشتراك',
  },
  notifications: {
    title: 'الإشعارات',
    empty: 'لا توجد إشعارات جديدة.',
    markAll: 'تعليم الكل كمقروء',
  },
  forgot: {
    title: 'إعادة تعيين كلمة المرور',
    sent: 'إذا كان هناك حساب مرتبط بـ {{email}}، تم إرسال رابط إعادة التعيين.',
    enterEmail: 'أدخل بريدك الإلكتروني في الأعلى أولًا.',
  },
};