import type { TranslationSchema } from './en';

export const ar: TranslationSchema = {
  common: {
    appName: 'بروبرتي بَلس',
    cancel: 'إلغاء',
    save: 'حفظ',
    retry: 'إعادة المحاولة',
    seeAll: 'عرض الكل',
    loading: 'جارٍ التحميل…',
    error: 'حدث خطأ ما',
    back: 'رجوع',
    done: 'تم',
    currency: 'ج.م',
    forSale: 'للبيع',
    forRent: 'للإيجار',
  },
  tabs: {
    home: 'الرئيسية',
    search: 'بحث',
    ai: 'المستشار',
    portfolio: 'محفظتي',
    profile: 'حسابي',
  },
  auth: {
    welcome: 'أهلاً بعودتك',
    welcomeSub: 'سجّل الدخول إلى لوحة استثماراتك',
    createAccount: 'أنشئ حسابك',
    createSub: 'ابدأ رحلتك في الاستثمار العقاري المميّز اليوم.',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    continueWithGoogle: 'المتابعة عبر Google',
    or: 'أو',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    forgotPassword: 'نسيت كلمة المرور؟',
    signOut: 'تسجيل الخروج',
    emailRequired: 'من فضلك أدخل بريدًا صحيحًا',
    passwordRequired: 'كلمة المرور 8 أحرف على الأقل',
    nameRequired: 'من فضلك أدخل اسمك',
  },
  landing: {
    title: 'استثمر في العقارات المصرية والذكاء الاصطناعي في صفّك.',
    subtitle: 'تقارير ذكية مبنية على بيانات حقيقية، تحليل القيمة العادلة، ومستشار سوق — كله من عقارات فعلية.',
    getStarted: 'ابدأ الآن',
    signIn: 'تسجيل الدخول',
    f1: 'تقارير ذكية بتوصية شراء/انتظار/تجنّب وتوقّع 5 سنوات.',
    f2: 'اتجاهات سوق حقيقية وعوائد ومقارنات القيمة العادلة.',
    f3: 'مستشار يجيب من بيانات حقيقية فعلية.',
  },
  forgot: {
    title: 'إعادة تعيين كلمة المرور',
    sent: 'إذا كان هناك حساب لـ {{email}} فقد أُرسل رابط إعادة التعيين.',
    enterEmail: 'أدخل بريدك بالأعلى أولاً.',
  },
  home: {
    welcomeBack: 'أهلاً بعودتك',
    greetingMorning: 'صباح الخير',
    greetingAfternoon: 'مساء الخير',
    greetingEvening: 'مساء الخير',
    aiInsight: 'اسأل المستشار الذكي',
    aiInsightBody: 'إجابات مبنية على بيانات حقيقية عن العوائد والمخاطر وأين تستثمر.',
    topOpportunities: 'أفضل الفرص',
    dashTitle: 'لوحة التحكم',
    portfolioValue: 'قيمة المحفظة',
    thisMonth: '+{{value}}% هذا الشهر',
    rentalYield: 'العائد الإيجاري',
    benchmark: 'المعيار {{value}}%',
    propertiesTracked: 'عقارات متابَعة',
    aiMarketScore: 'تقييم السوق الذكي',
    activePortfolio: 'المحفظة النشطة',
    portfolioEmpty: 'لا توجد عقارات محفوظة بعد. أضف من البحث لمتابعتها هنا.',
    high: 'مرتفع',
    stable: 'مستقر',
    low: 'منخفض',
  },
  market: {
    title: 'اتجاهات السوق',
    totalValue: 'إجمالي قيمة السوق',
    activeListings: 'العروض النشطة',
    avgPrice: 'متوسط السعر',
    appreciation: 'نسبة الارتفاع',
    priceTrend: 'اتجاه متوسط سعر المتر',
    topDistricts: 'أعلى المناطق',
    byType: 'حسب نوع العقار',
  },
  search: {
    title: 'بحث الاستثمار',
    subtitle: '{{count}} عقار يطابق استراتيجيتك',
    filtersTitle: 'الفلاتر',
    city: 'المدينة',
    area: 'المنطقة',
    type: 'النوع',
    beds: 'غرف',
    allCities: 'كل المدن',
    allAreas: 'كل المناطق',
    allTypes: 'كل الأنواع',
    any: 'الكل',
    priceRange: 'نطاق السعر (ج.م)',
    minPrice: 'أقل سعر',
    maxPrice: 'أعلى سعر',
    apply: 'تطبيق',
    reset: 'إعادة ضبط',
    noResults: 'لا توجد عقارات. جرّب تعديل الفلاتر.',
  },
  detail: {
    beds: 'غرف',
    baths: 'حمامات',
    area: 'المساحة',
    year: 'السنة',
    investmentSnapshot: 'لمحة استثمارية',
    netYield: 'العائد الصافي',
    fiveYearRoi: 'عائد 5 سنوات',
    cashOnCash: 'العائد النقدي',
    pricePerSqm: 'سعر المتر',
    runAiAnalysis: 'تشغيل التحليل الذكي',
    generateReport: 'إنشاء تقرير ذكي',
    contact: 'تواصل',
    addToPortfolio: 'أضف للمحفظة',
    inPortfolio: 'في المحفظة',
    about: 'عن هذا العقار',
  },
  inquiry: {
    title: 'تواصل معنا',
    name: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    message: 'الرسالة',
    viewing: 'طلب معاينة',
    contact: 'مراسلة الوكيل',
    submit: 'إرسال الطلب',
    sent: 'تم إرسال الطلب',
    sentBody: 'سيتواصل معك الوكيل قريبًا.',
    nameRequired: 'من فضلك أدخل اسمك',
  },
  advisor: {
    title: 'المستشار الذكي',
    subtitle: 'إجابات موثوقة عن السوق المصري ومحفظتك.',
    greeting: 'أهلاً! أنا مستشارك في بروبرتي بَلس. اسألني عن العوائد والمخاطر والمناطق وأين تستثمر.',
    placeholder: 'اسأل عن السوق…',
    s1: 'أين أعلى العوائد؟',
    s2: 'هل القاهرة الجديدة مبالغ في سعرها؟',
    s3: 'كيف أنوّع استثماراتي؟',
  },
  analysis: {
    title: 'التحليل الذكي',
    report: 'تقرير ذكي',
    negotiation: 'التفاوض',
    financing: 'التمويل',
    reportTitle: 'تقرير استثماري ذكي',
    reportBody: 'احصل على توصية كاملة (شراء/انتظار/تجنّب) مع المخاطر وتوقّع 5 سنوات.',
    negoTitle: 'نصائح التفاوض',
    negoBody: 'اعرف القيمة العادلة وعرضًا مقترحًا للبدء ونقاط تفاوض موثوقة.',
    getTips: 'احصل على نصائح التفاوض',
    askingPrice: 'السعر المطلوب',
    fairValue: 'القيمة العادلة',
    suggestedOffer: 'العرض المقترح',
    vsMarket: 'مقابل السوق',
    financingBody: 'قارن طرق تمويل هذا العقار وتأثير كل منها على عائدك.',
    cash: 'شراء كاش',
    installments: 'تقسيط المطوّر',
    mortgage: 'قرض بنكي',
    downPayment: 'المقدّم',
    monthlyPayment: 'القسط الشهري',
    monthlyCashFlow: 'التدفّق النقدي الشهري',
    term: 'مدة السداد',
    years: '{{count}} سنوات',
    oneTime: 'دفعة واحدة',
  },
  report: {
    title: 'التقرير الاستثماري',
    recommendation: 'التوصية',
    buy: 'شراء',
    hold: 'انتظار',
    avoid: 'تجنّب',
    keyMetrics: 'المؤشرات الرئيسية',
    grossYield: 'العائد الإجمالي',
    netYield: 'العائد الصافي',
    capRate: 'معدل الرسملة',
    cashOnCash: 'العائد النقدي',
    monthlyCashFlow: 'التدفّق الشهري',
    fiveYearRoi: 'عائد 5 سنوات',
    breakEven: 'نقطة التعادل',
    riskLevel: 'تقييم المخاطر',
    riskScore: 'الدرجة {{score}}/100',
    trend: 'اتجاه السعر 5 سنوات',
    sources: 'المصادر',
    generating: 'جارٍ إنشاء تقريرك…',
    generatingBody: 'يقوم الذكاء الاصطناعي بتحليل السوق والمقارنات والمخاطر.',
    limitTitle: 'تم بلوغ الحد الشهري',
    limitBody: 'تشمل الباقة المجانية تقريرَين ذكيَّين شهريًّا. ارتقِ إلى Pro للحصول على تقارير غير محدودة.',
    upgrade: 'الترقية إلى Pro',
    myReports: 'التقارير الاستثمارية',
    empty: 'لا توجد تقارير بعد. أنشئ تقريرًا من صفحة العقار.',
    confidenceLabel: 'الثقة: {{value}}%',
    deleteConfirm: 'حذف هذا التقرير؟',
    delete: 'حذف',
    generatedOn: 'أُنشئ في {{date}}',
  },
  portfolio: {
    title: 'محفظتك',
    count: '{{count}} عقار محفوظ',
    totalValue: 'القيمة الإجمالية',
    holdings: 'الأصول',
    compare: 'مقارنة',
    compareN: 'قارن {{count}} عقارات',
    selectHint: 'اختر 2–4 عقارات للمقارنة (تم اختيار {{count}})',
    explore: 'استكشف العقارات',
    empty: 'لا عقارات محفوظة بعد. أضف من البحث.',
  },
  compare: {
    title: 'مقارنة ذكية',
    analyzing: 'جارٍ مقارنة العقارات…',
    verdict: 'حكم الذكاء الاصطناعي',
    save: 'حفظ المقارنة',
    saved: 'محفوظة',
    savedTitle: 'المقارنات المحفوظة',
    savedEmpty: 'لا توجد مقارنات محفوظة بعد. قارن عقارات واضغط حفظ.',
    properties: '{{count}} عقارات',
    pricePerSqm: 'سعر المتر',
    upgrade: 'الترقية إلى Pro',
    limitTitle: 'تم بلوغ الحد الشهري',
    limitBody: 'تشمل الباقة المجانية مقارنةً واحدةً شهريًّا. ارتقِ إلى Pro للحصول على مقارنات غير محدودة.',
  },
  pricing: {
    title: 'الباقات والأسعار',
    subtitle: 'ارتقِ للحصول على تقارير ذكية غير محدودة والمستشار الكامل وبيانات لحظية.',
    free: 'مجاني',
    popular: 'الأكثر شيوعًا',
    current: 'باقتك الحالية',
    checkout: 'الدفع',
    subtotal: 'الإجمالي الفرعي',
    vat: 'ضريبة (14%)',
    total: 'الإجمالي',
    payStripe: 'ادفع عبر Stripe',
    secured: 'دفع آمن مشفّر 256-bit SSL',
    successTitle: 'تم الدفع بنجاح',
    successBody: 'اشتراك {{plan}} مُفعّل الآن.',
    failedTitle: 'فشل الدفع',
    failedBody: 'من فضلك حاول مرة أخرى.',
  },
  profile: {
    title: 'حسابي',
    investor: 'مستثمر',
    theme: 'المظهر',
    themeLight: 'فاتح',
    themeDark: 'غامق',
    themeSystem: 'النظام',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    viewReports: 'عرض التقارير',
    rtlTitle: 'يلزم إعادة التشغيل',
    rtlBody: 'من فضلك أغلق التطبيق وأعد فتحه لتطبيق اتجاه من اليمين لليسار.',
    signOutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',
  },
  admin: {
    title: 'الإدارة',
    properties: 'العقارات',
    inquiries: 'الاستفسارات',
    users: 'المستخدمون',
    newProperty: 'عقار جديد',
    editProperty: 'تعديل العقار',
    deleteTitle: 'حذف هذا العقار؟',
    delete: 'حذف',
    status: 'الحالة',
    featured: 'مميّز',
    approved: 'معتمد',
    fTitle: 'العنوان',
    fPrice: 'السعر (ج.م)',
    fArea: 'المساحة (م²)',
    fAddress: 'العنوان',
    titleRequired: 'العنوان مطلوب',
    noAccess: 'ليس لديك صلاحية الإدارة.',
    noInquiries: 'لا استفسارات بعد.',
    setStatus: 'تغيير الحالة',
    plan: 'الخطة',
    deleteInquiryTitle: 'حذف هذا الاستفسار؟',
  },
};
