export const en = {
  common: {
    appName: 'PropertyPulse',
    cancel: 'Cancel',
    save: 'Save',
    retry: 'Retry',
    seeAll: 'See all',
    loading: 'Loading…',
    error: 'Something went wrong',
    back: 'Back',
    done: 'Done',
    currency: 'EGP',
    forSale: 'For Sale',
    forRent: 'For Rent',
  },
  tabs: {
    home: 'Home',
    search: 'Search',
    ai: 'Advisor',
    portfolio: 'Portfolio',
    profile: 'Profile',
  },
  notif: {
    title: 'Notifications',
    empty: 'No notifications yet.',
    removed: 'This inquiry was removed by the team.',
    adm: { newInquiry: 'New inquiry', newUser: 'New user signed up' },
    tag: { inquiry: 'Inquiry', user: 'User' },
    kind: {
      buyer_inquiry: 'Buyer Inquiry',
      viewing_request: 'Viewing Request',
      contact_message: 'Contact Message',
      application: 'Application',
    },
    status: { new: 'New', in_progress: 'In Progress', closed: 'Closed', deleted: 'Deleted' },
  },
  propertyType: {
    apartment: 'Apartment',
    villa: 'Villa',
    house: 'House',
    townhouse: 'Townhouse',
    commercial: 'Commercial',
    land: 'Land',
  },
  listingStatus: {
    for_sale: 'For Sale',
    for_rent: 'For Rent',
    sold: 'Sold',
    off_market: 'Off Market',
  },
  unit: {
    bed: 'bed',
    beds: 'beds',
    bath: 'bath',
    baths: 'baths',
    sqm: 'm²',
    yrs: 'yrs',
  },
  risk: {
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
  },
  plan: {
    free: 'Free',
    pro: 'Pro',
  },
  role: {
    admin: 'Admin',
    investor: 'Investor',
    user: 'User',
  },
  auth: {
    welcome: 'Welcome back',
    welcomeSub: 'Sign in to your investment dashboard',
    createAccount: 'Create your account',
    createSub: 'Start your journey into premium real estate investment today.',
    email: 'Email address',
    password: 'Password',
    fullName: 'Full name',
    signIn: 'Sign in',
    signUp: 'Sign up',
    continueWithGoogle: 'Continue with Google',
    completingSignIn: 'Completing sign-in…',
    googleFailedTitle: "Google sign-in didn't complete",
    googleFailedBody: "We couldn't finish signing you in with Google. Please try again, or sign in with your email.",
    or: 'or',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    forgotPassword: 'Forgot password?',
    signOut: 'Sign out',
    emailRequired: 'Please enter a valid email',
    passwordRequired: 'Password must be at least 8 characters',
    nameRequired: 'Please enter your name',
  },
  landing: {
    title: 'Invest in Egyptian real estate with AI on your side.',
    subtitle: 'Grounded AI reports, fair-value analysis and a market advisor — all from real listings data.',
    getStarted: 'Get started',
    signIn: 'Sign in',
    f1: 'AI reports with buy / hold / avoid and a 5-year outlook.',
    f2: 'Real market trends, yields and fair-value comparisons.',
    f3: 'A grounded advisor that answers from real data.',
  },
  forgot: {
    title: 'Reset password',
    sent: 'If an account exists for {{email}}, a reset link has been sent.',
    enterEmail: 'Enter your email above first.',
  },
  home: {
    welcomeBack: 'WELCOME BACK',
    greetingMorning: 'Good Morning',
    greetingAfternoon: 'Good Afternoon',
    greetingEvening: 'Good Evening',
    aiInsight: 'Ask the AI Advisor',
    aiInsightBody: 'Get grounded answers on yields, risks and where to allocate next.',
    topOpportunities: 'Top Opportunities',
    dashTitle: 'Dashboard',
    portfolioValue: 'Portfolio Value',
    thisMonth: '+{{value}}% this month',
    rentalYield: 'Rental Yield',
    benchmark: 'Benchmark {{value}}%',
    propertiesTracked: 'Properties Tracked',
    aiMarketScore: 'AI Market Score',
    activePortfolio: 'Active Portfolio',
    portfolioEmpty: 'No saved properties yet. Add some from Search to track them here.',
    high: 'High',
    stable: 'Stable',
    low: 'Low',
  },
  market: {
    title: 'Market Trends',
    totalValue: 'Total Market Value',
    activeListings: 'Active Listings',
    avgPrice: 'Avg. Price',
    appreciation: 'Appreciation',
    priceTrend: 'Median price / m² trend',
    topDistricts: 'Top Districts',
    byType: 'By Property Type',
  },
  search: {
    title: 'Investment Search',
    subtitle: '{{count}} properties match your strategy',
    filtersTitle: 'Filters',
    city: 'City',
    area: 'Area',
    type: 'Type',
    beds: 'Beds',
    allCities: 'All cities',
    allAreas: 'All areas',
    allTypes: 'All types',
    any: 'Any',
    priceRange: 'Price range (EGP)',
    minPrice: 'Min price',
    maxPrice: 'Max price',
    apply: 'Apply',
    reset: 'Reset',
    noResults: 'No properties found. Try adjusting your filters.',
  },
  detail: {
    beds: 'Beds',
    baths: 'Baths',
    area: 'Area',
    year: 'Year',
    investmentSnapshot: 'Investment Snapshot',
    netYield: 'Net Yield',
    fiveYearRoi: '5-Year ROI',
    cashOnCash: 'Cash-on-Cash',
    pricePerSqm: 'Price / m²',
    runAiAnalysis: 'Run AI Analysis',
    generateReport: 'Generate AI Report',
    contact: 'Contact',
    addToPortfolio: 'Add to Portfolio',
    inPortfolio: 'In Portfolio',
    about: 'About this property',
  },
  inquiry: {
    title: 'Get in touch',
    name: 'Full name',
    email: 'Email',
    phone: 'Phone',
    message: 'Message',
    viewing: 'Request viewing',
    contact: 'Contact agent',
    submit: 'Send request',
    sent: 'Request sent',
    sentBody: 'The agent will get back to you shortly.',
    nameRequired: 'Please enter your name',
  },
  advisor: {
    title: 'AI Advisor',
    subtitle: 'Grounded answers about the Egyptian market & your portfolio.',
    greeting: "Hello! I'm your PropertyPulse advisor. Ask me about yields, risk, neighborhoods or where to invest next.",
    placeholder: 'Ask about the market…',
    s1: 'Where are the best yields?',
    s2: 'Is New Cairo overpriced?',
    s3: 'How should I diversify?',
  },
  analysis: {
    title: 'AI Analysis',
    report: 'AI Report',
    negotiation: 'Negotiation',
    financing: 'Financing',
    reportTitle: 'AI Investment Report',
    reportBody: 'Generate a full buy/hold/avoid recommendation with risk and a 5-year outlook.',
    negoTitle: 'Negotiation Tips',
    negoBody: 'See the fair value, a suggested opening offer and grounded talking points.',
    getTips: 'Get negotiation tips',
    askingPrice: 'Asking Price',
    fairValue: 'Fair Value',
    suggestedOffer: 'Suggested Offer',
    vsMarket: 'vs. Market',
    financingBody: 'Compare ways to finance this property and how each affects your return.',
    cash: 'Cash Purchase',
    installments: 'Developer Installments',
    mortgage: 'Bank Mortgage',
    downPayment: 'Down Payment',
    monthlyPayment: 'Monthly Payment',
    monthlyCashFlow: 'Monthly Cash Flow',
    term: 'Term',
    years: '{{count}} yrs',
    oneTime: 'One payment',
  },
  report: {
    title: 'Investment Report',
    recommendation: 'RECOMMENDATION',
    buy: 'Buy',
    hold: 'Hold',
    avoid: 'Avoid',
    keyMetrics: 'Key Metrics',
    grossYield: 'Gross Yield',
    netYield: 'Net Yield',
    capRate: 'Cap Rate',
    cashOnCash: 'Cash-on-Cash',
    monthlyCashFlow: 'Monthly Cash Flow',
    fiveYearRoi: '5-Year ROI',
    breakEven: 'Break-even',
    riskLevel: 'Risk Assessment',
    riskScore: 'Score {{score}}/100',
    trend: '5-Year Price Trend',
    sources: 'Sources',
    generating: 'Generating your report…',
    generatingBody: 'Our multi-agent AI is analyzing the market, comps and risk.',
    limitTitle: 'Monthly limit reached',
    limitBody: 'Free plan includes 2 AI reports per month. Upgrade to Pro for unlimited reports.',
    upgrade: 'Upgrade to Pro',
    myReports: 'Investment Reports',
    empty: 'No reports yet. Generate one from a property page.',
    confidenceLabel: 'Confidence: {{value}}%',
    deleteConfirm: 'Delete this report?',
    delete: 'Delete',
    generatedOn: 'Generated {{date}}',
  },
  portfolio: {
    title: 'Your Portfolio',
    count: '{{count}} saved properties',
    totalValue: 'Total Value',
    holdings: 'Holdings',
    compare: 'Compare',
    compareN: 'Compare {{count}} properties',
    selectHint: 'Select 2–4 properties to compare ({{count}} selected)',
    explore: 'Explore properties',
    empty: 'No saved properties yet. Add some from search.',
  },
  compare: {
    title: 'AI Compare',
    analyzing: 'Comparing properties…',
    verdict: 'AI VERDICT',
    save: 'Save comparison',
    saved: 'Saved',
    savedTitle: 'Saved Comparisons',
    savedEmpty: 'No saved comparisons yet. Compare properties and tap Save.',
    properties: '{{count}} properties',
    pricePerSqm: 'Price / m²',
    reasoning: 'AI Reasoning',
    upgrade: 'Upgrade to Pro',
    limitTitle: 'Monthly limit reached',
    limitBody: 'Free plan includes 1 AI comparison per month. Upgrade to Pro for unlimited comparisons.',
  },
  pricing: {
    title: 'Plans & Pricing',
    subtitle: 'Upgrade for unlimited AI reports, the full advisor and real-time data.',
    free: 'Free',
    popular: 'Popular',
    current: 'Current plan',
    freeTier: 'Base',
    proTier: 'Elevate',
    freeCadence: 'Forever free',
    proCadence: 'per month',
    freeFeatures: ['Basic search', '2 AI reports / month', '1 AI comparison / month', 'Limited market data'],
    proFeatures: ['Unlimited AI reports', 'Full AI advisor', 'Real-time trends', 'Portfolio tools'],
    checkout: 'Checkout',
    subtotal: 'Subtotal',
    vat: 'VAT (14%)',
    total: 'Total',
    payStripe: 'Pay with Stripe',
    secured: 'Secure 256-bit SSL payment',
    successTitle: 'Payment successful',
    successBody: 'Your {{plan}} subscription is now active.',
    failedTitle: 'Payment failed',
    failedBody: 'Please try again.',
  },
  profile: {
    title: 'Profile',
    investor: 'Investor',
    theme: 'Appearance',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    viewReports: 'View Reports',
    rtlTitle: 'Restart required',
    rtlBody: 'Please fully close and reopen the app to apply right-to-left layout.',
    signOutConfirm: 'Are you sure you want to sign out?',
  },
  admin: {
    title: 'Admin',
    properties: 'Properties',
    inquiries: 'Inquiries',
    users: 'Users',
    newProperty: 'New property',
    editProperty: 'Edit property',
    deleteTitle: 'Delete this property?',
    delete: 'Delete',
    status: 'Status',
    featured: 'Featured',
    approved: 'Approved',
    fTitle: 'Title',
    fPrice: 'Price (EGP)',
    fArea: 'Area (m²)',
    fAddress: 'Address',
    titleRequired: 'Title is required',
    noAccess: 'You do not have admin access.',
    noInquiries: 'No inquiries yet.',
    setStatus: 'Set status',
    plan: 'Plan',
    deleteInquiryTitle: 'Delete this inquiry?',
  },
};

export type TranslationSchema = typeof en;
