export const en = {
  common: {
    appName: 'PropertyPulse',
    cancel: 'Cancel',
    save: 'Save',
    retry: 'Retry',
    seeAll: 'See all',
    loading: 'Loading…',
    error: 'Something went wrong',
    search: 'Search areas or properties…',
    currency: 'EGP',
    verified: 'Verified',
    readyToMove: 'Ready to Move',
    offPlan: 'Off-Plan',
    startingFrom: 'STARTING FROM',
    viewMap: 'View map',
    demoMode: 'Demo mode — connect Supabase to go live',
  },
  tabs: {
    home: 'Home',
    search: 'Search',
    ai: 'AI',
    portfolio: 'Portfolio',
    profile: 'Profile',
  },
  auth: {
    welcome: 'Welcome back',
    welcomeSub: 'Sign in to your investment dashboard',
    createAccount: 'Create your account',
    createSub: 'Start your journey into premium real estate investment today.',
    createAccountCta: 'Create Account',
    email: 'Email address',
    password: 'Password',
    fullName: 'Full name',
    fullNamePlaceholder: 'Enter your full name',
    investorType: 'Investor type',
    investorIndividual: 'Individual',
    investorInstitutional: 'Institutional',
    investorFamilyOffice: 'Family Office',
    termsPrefix: 'By creating an account, you agree to our',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    and: 'and',
    signIn: 'Sign in',
    signUp: 'Sign up',
    login: 'Login',
    continueWithGoogle: 'Continue with Google',
    or: 'or',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    forgotPassword: 'Forgot password?',
    confirmEmail: 'Check your inbox to confirm your email, then sign in.',
    signOut: 'Sign out',
    emailRequired: 'Please enter a valid email',
    passwordRequired: 'Password must be at least 8 characters',
    nameRequired: 'Please enter your name',
  },
  home: {
    greetingMorning: 'Good Morning',
    greetingAfternoon: 'Good Afternoon',
    greetingEvening: 'Good Evening',
    welcomeBack: 'WELCOME BACK',
    portfolioValue: 'PORTFOLIO VALUE',
    netYield: 'NET YIELD',
    properties: 'PROPERTIES',
    aiInsight: 'AI INSIGHT',
    aiInsightBody:
      'Commercial yields in New Cairo are projected to rise by 15% next quarter. Consider reallocating residential capital.',
    viewStrategy: 'View strategy',
    topOpportunities: 'Top Opportunities',
    marketActivity: 'Market Activity',
    rentalIncome: 'Rental Income',
    mortgagePayment: 'Mortgage Payment',
  },
  search: {
    title: 'Investment Opportunities',
    subtitle: '{{count}} properties matching your portfolio strategy',
    filters: {
      price: 'Price',
      type: 'Type',
      bedrooms: 'Bedrooms',
    },
    noResults: 'No properties found. Try adjusting your filters.',
    dealScore: 'Deal Score',
  },
  detail: {
    pulseScore: 'PULSE SCORE',
    projectedRoi: 'Projected ROI',
    grossYield: 'Gross Yield',
    ltvRatio: 'LTV Ratio',
    riskLevel: 'Risk Level',
    aiThesis: 'AI INVESTMENT THESIS',
    highlights: 'PROPERTY HIGHLIGHTS',
    location: 'LOCATION',
    beds: 'Beds',
    baths: 'Baths',
    area: 'Area',
    addToPortfolio: 'Add to Portfolio',
    inPortfolio: 'In Portfolio',
    generateReport: 'Generate Report',
    riskLow: 'Low',
    riskModerate: 'Moderate',
    riskHigh: 'High',
  },
  chat: {
    title: 'AI Advisor',
    online: 'Online',
    today: 'Today',
    greeting:
      "Hello! I've analyzed your current portfolio. Your real estate assets have seen a 6.2% yield increase this quarter. Would you like a breakdown of the top performers?",
    placeholder: 'Ask about your properties…',
    suggestions: {
      risks: 'Market risks?',
      diversify: 'Diversify portfolio',
      tax: 'Tax implications',
    },
  },
  portfolio: {
    title: 'Your Portfolio',
    updated: 'Performance update for {{month}}',
    totalValue: 'TOTAL ASSET VALUE',
    avgYield: 'AVG. YIELD',
    cashFlow: 'CASH FLOW',
    equityGrowth: 'Equity Growth',
    last6: 'Last 6 Months',
    holdings: 'Holdings',
    manage: 'Manage Portfolio',
    transactions: 'View Transaction History',
    empty: 'You have no holdings yet. Explore opportunities to get started.',
  },
  profile: {
    title: 'Profile',
    account: 'Account',
    preferences: 'Preferences',
    theme: 'Appearance',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    adminDashboard: 'Admin Dashboard',
    notifications: 'Notifications',
    about: 'About',
    member: 'Member since {{date}}',
  },
  admin: {
    title: 'Admin Dashboard',
    label: 'ADMIN DASHBOARD',
    welcomeBack: 'Welcome back, {{name}}',
    director: 'Director',
    overview: 'Overview',
    totalUsers: 'Total Users',
    users: 'USERS',
    listings: 'LISTINGS',
    reports: 'REPORTS',
    revenue: 'REVENUE',
    totalProperties: 'Properties',
    activeToday: 'Active Today',
    recentActivity: 'Recent Activity',
    viewAll: 'VIEW ALL',
    recentUsers: 'Recent Users',
    manageProperties: 'Manage Properties',
    manageUsers: 'Manage Users',
    searchUsers: 'Search users…',
    changeRole: 'Change role',
    roleUpdated: "{{name}}'s role is now {{role}}",
    roleError: 'Could not update role',
    cannotSelf: 'You cannot change your own role.',
    role: 'Role',
    joined: 'Joined',
    noAccess: 'You do not have admin access.',
    roles: {
      investor: 'Investor',
      consultant: 'Consultant',
      admin: 'Admin',
    },
    activity: {
      report: 'Generated Q3 Yield Report',
      listing: 'Listed New Property',
      profile: 'Updated Investment Profile',
      discrepancy: 'Flagged Listing Discrepancy',
    },
  },
  payment: {
    title: 'Payment',
    selectedPlan: 'SELECTED PLAN',
    perMonth: '/month',
    method: 'PAYMENT METHOD',
    card: 'Card Payment',
    vodafone: 'Vodafone Cash',
    fawry: 'Fawry',
    cardHolder: 'CARD HOLDER NAME',
    cardHolderPlaceholder: 'Full name on card',
    cardNumber: 'CARD NUMBER',
    expiry: 'EXPIRY DATE',
    cvv: 'CVV',
    saveCard: 'Save card information for faster checkout',
    subscriptionFee: 'Subscription Fee',
    serviceTax: 'Service Tax (14%)',
    orderTotal: 'Order Total',
    payNow: 'PAY {{amount}} NOW',
    secure: 'Secure 256-bit SSL Encrypted Payment',
    vodafoneHint: 'You will be redirected to confirm via your Vodafone Cash wallet.',
    fawryHint: 'A Fawry reference code will be generated for payment at any outlet.',
    success: 'Payment successful',
    successBody: 'Your {{plan}} subscription is now active.',
    failed: 'Payment failed. Please try again.',
    pending: 'Payment is pending confirmation.',
    phone: 'Wallet phone number',
    upgrade: 'Upgrade Plan',
    planName: 'Institutional AI',
    feature1: 'Real-time market volatility AI analysis',
    feature2: 'Unlimited property yield simulations',
    feature3: 'Direct human-analyst concierge access',
  },
  report: {
    title: 'Investment Report',
    generating: 'Generating report…',
    recommendation: 'RECOMMENDATION',
    confidence: '{{value}}% confidence',
    summary: 'SUMMARY',
    keyMetrics: 'KEY METRICS',
    grossYield: 'Gross Yield',
    netYield: 'Net Yield',
    capRate: 'Cap Rate',
    cashOnCash: 'Cash on Cash',
    monthlyCashFlow: 'Monthly Cash Flow',
    fiveYearRoi: '5-Year ROI',
    riskLevel: 'Risk Level',
    buy: 'BUY',
    hold: 'HOLD',
    avoid: 'AVOID',
    generatedAt: 'Generated {{date}}',
  },
  transactions: {
    title: 'Transaction History',
    empty: 'No transactions yet.',
    rental: 'Rental Income',
    mortgage: 'Mortgage Payment',
    purchase: 'Property Purchase',
    subscription: 'Subscription',
  },
  notifications: {
    title: 'Notifications',
    empty: "You're all caught up.",
    markAll: 'Mark all as read',
  },
  forgot: {
    title: 'Reset password',
    sent: 'If an account exists for {{email}}, a reset link has been sent.',
    enterEmail: 'Enter your email above first.',
  },
};

export type TranslationSchema = typeof en;